package com.example.sauexpert.dimensions

import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.TextUnit
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

class Dimensions(
    val grid_0_25: Dp,
    val grid_0_5: Dp,
    val grid_1: Dp,
    val grid_1_5: Dp,
    val grid_2: Dp,
    val grid_2_5: Dp,
    val grid_3: Dp,
    val grid_3_5: Dp,
    val grid_4: Dp,
    val grid_4_5: Dp,
    val grid_5: Dp,
    val grid_5_5: Dp,
    val grid_6: Dp,
    val plane_0: Dp,
    val plane_1: Dp,
    val plane_2: Dp,
    val plane_3: Dp,
    val plane_4: Dp,
    val plane_5: Dp,
    val imageWidth_0: Dp,
    val imageWidth_1: Dp,
    val imageHeight_0: Dp,
    val imageHeight_1: Dp,
    val buttonHeight: Dp,
    val fontSizeSubtitle_2: TextUnit,
    val fontSizeBody_1: TextUnit,
    val fontSizeCaption: TextUnit,
    val minimum_touch_target: Dp = 48.dp,
)

val smallDimensions = Dimensions(
    grid_0_25 = 1.5f.dp,
    grid_0_5 = 3.dp,
    grid_1 = 6.dp,
    grid_1_5 = 9.dp,
    grid_2 = 12.dp,
    grid_2_5 = 15.dp,
    grid_3 = 18.dp,
    grid_3_5 = 21.dp,
    grid_4 = 24.dp,
    grid_4_5 = 27.dp,
    grid_5 = 30.dp,
    grid_5_5 = 33.dp,
    grid_6 = 36.dp,
    plane_0 = 0.dp,
    plane_1 = 1.dp,
    plane_2 = 2.dp,
    plane_3 = 3.dp,
    plane_4 = 6.dp,
    plane_5 = 12.dp,
    imageWidth_0 = 45.dp,
    imageWidth_1 = 110.dp,
    imageHeight_0 = 40.dp,
    imageHeight_1 = 210.dp,
    buttonHeight = 38.dp,
    fontSizeSubtitle_2 = 14.sp,
    fontSizeBody_1 = 14.sp,
    fontSizeCaption = 19.sp
)

val sw360Dimensions = Dimensions(
    grid_0_25 = 2.dp,
    grid_0_5 = 4.dp,
    grid_1 = 8.dp,
    grid_1_5 = 12.dp,
    grid_2 = 16.dp,
    grid_2_5 = 20.dp,
    grid_3 = 24.dp,
    grid_3_5 = 28.dp,
    grid_4 = 32.dp,
    grid_4_5 = 36.dp,
    grid_5 = 40.dp,
    grid_5_5 = 44.dp,
    grid_6 = 48.dp,
    plane_0 = 0.dp,
    plane_1 = 1.dp,
    plane_2 = 2.dp,
    plane_3 = 4.dp,
    plane_4 = 8.dp,
    plane_5 = 16.dp,
    imageWidth_0 = 65.dp,
    imageWidth_1 = 130.dp,
    imageHeight_0 = 50.dp,
    imageHeight_1 = 275.dp,
    buttonHeight = 50.dp,
    fontSizeSubtitle_2 = 17.sp,
    fontSizeBody_1 = 17.sp,
    fontSizeCaption = 22.sp
)
